import './globals.css'
import { HeaderComponent } from './layout/HeaderComponent'
import { NavBar } from './layout/NavBar'

export const metadata = {
  title: 'Moshal HomePage',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <div className="bg-white flex flex-col items-center w-full">
          <div className="bg-white w-[430px] h-[932px] flex flex-col">
        <HeaderComponent/>
        <NavBar/>

        {children}
        </div>
        </div>
        </body>
    </html>
  )
}
